services:
    web:
        build: ./web/
        ports:
            - "80:80"
        depends_on:
            - server
        networks:
            - ide-net

    server:
        build: .
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - ide-net

    postgres:
        image: postgres:17.2-alpine3.21
        restart: always
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 10s
            retries: 5
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - ide-net

    redis:
        image: redis:7.4.2-alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - ide-net

networks:
    ide-net:

volumes:
    pg-data:
    redis-data:
