services:
    web:
        build: ./web/
        ports:
            - "80:80"
        depends_on:
            - api-server
        networks:
            - ide-net

    api-server:
        build: .
        ports:
            - "8000:8000" # Just for debugging deployment in dev, delete this on server
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - MODE=production
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        networks:
            - ide-net

    rpc-server-1:
        build: ./executor/.
        networks:
            - ide-net

    rpc-server-2:
        build: ./executor/.
        networks:
            - ide-net

    rpc-server-3:
        build: ./executor/.
        networks:
            - ide-net

    rpc-proxy:
        image: nginx:1.27.4-alpine
        volumes:
            - ./balancer/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - rpc-server-1
            - rpc-server-2
            - rpc-server-3
        networks:
            - ide-net

    postgres:
        image: postgres:17.2-alpine3.21
        restart: always
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            retries: 5
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - ide-net

    redis:
        image: redis:7.4.2-alpine
        restart: always
        volumes:
            - redis-data:/data
        networks:
            - ide-net

networks:
    ide-net:

volumes:
    pg-data:
    redis-data:
